#!/usr/bin/env bash

if
  [[ -s "/home/appurify/.rvm/gems/jruby-1.7.10@global/environment" ]]
then
  source "/home/appurify/.rvm/gems/jruby-1.7.10@global/environment"
  exec cucumber "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/appurify/.rvm/gems/jruby-1.7.10@global/environment'" >&2
  exit 1
fi
