language: ruby
rvm:
  - 2.1.0
before_install:
  - "head -n 100 /etc/rvmrc ~/.rvmrc || true"
  - "env | grep '^rvm' || true"
install: gem install tf -v '>=0.4.1'
before_script:
  - "sudo chown -R $USER: $rvm_path"
  - "sudo apt-get install gawk -y"
  - "echo ruby_1.8.7_rubygems_version=1.8.25 > $rvm_path/user/db"
  - "sed -i'' -r -e '/rvm_silence_path_mismatch_check_flag|rvm_project_rvmrc/ d' ~/.rvmrc"
  - unset rvm_silence_path_mismatch_check_flag rvm_project_rvmrc
  - rvm alias delete default
  - rvm 1.9.3,1.9.3-p484 do rvm gemset reset_env
  - hash -r
  - ./install
  - rvm-smile
  - git submodule init
  - git submodule update
script: tf --text rvm-test/fast/* rvm-test-rvm1/*
notifications:
  irc:
    channels:
      - "irc.freenode.org#rvm-test"
  email:
    recipients:
      - mpapis@gmail.com
    on_failure: change
