#!/usr/bin/env bash

if
  [[ -s "/Users/appurify/.rvm/gems/ruby-2.1.1@global/environment" ]]
then
  source "/Users/appurify/.rvm/gems/ruby-2.1.1@global/environment"
  exec httpclient "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/appurify/.rvm/gems/ruby-2.1.1@global/environment'" >&2
  exit 1
fi
