#!/usr/bin/env bash

if
  [[ -s "/home/appurify/.rvm/gems/ruby-2.0.0-p353/environment" ]]
then
  source "/home/appurify/.rvm/gems/ruby-2.0.0-p353/environment"
  exec rake "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/appurify/.rvm/gems/ruby-2.0.0-p353/environment'" >&2
  exit 1
fi
